// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqselvTiVMXMG7ofEiHweXrlao4qGdG9Q',
    appId: '1:827104413595:web:d4c011670ce53eafb3833e',
    messagingSenderId: '827104413595',
    projectId: 'netra-dafdd',
    authDomain: 'netra-dafdd.firebaseapp.com',
    storageBucket: 'netra-dafdd.firebasestorage.app',
    measurementId: 'G-YG8YP8NLWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgGS74v7LcKCxrfuFe9whpb1QOTsENi1A',
    appId: '1:827104413595:android:d0ae443ffabf1df2b3833e',
    messagingSenderId: '827104413595',
    projectId: 'netra-dafdd',
    storageBucket: 'netra-dafdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTBX2AkkQKe4FJZdyufBdhv96fDKHHDZQ',
    appId: '1:827104413595:ios:30fa94e5dd5f8bcdb3833e',
    messagingSenderId: '827104413595',
    projectId: 'netra-dafdd',
    storageBucket: 'netra-dafdd.firebasestorage.app',
    iosClientId: '827104413595-ofvarcfsqmhj7cv9hnt87fm5ao2i8i8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.networkTrafficForecaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTBX2AkkQKe4FJZdyufBdhv96fDKHHDZQ',
    appId: '1:827104413595:ios:30fa94e5dd5f8bcdb3833e',
    messagingSenderId: '827104413595',
    projectId: 'netra-dafdd',
    storageBucket: 'netra-dafdd.firebasestorage.app',
    iosClientId: '827104413595-ofvarcfsqmhj7cv9hnt87fm5ao2i8i8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.networkTrafficForecaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqselvTiVMXMG7ofEiHweXrlao4qGdG9Q',
    appId: '1:827104413595:web:0364e64ad686c719b3833e',
    messagingSenderId: '827104413595',
    projectId: 'netra-dafdd',
    authDomain: 'netra-dafdd.firebaseapp.com',
    storageBucket: 'netra-dafdd.firebasestorage.app',
    measurementId: 'G-NPYDHZQVFJ',
  );
}
